### ISSUE TITLE
Roadmap: script and Docker

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/tuxml-kci#1]
We want a script to do something like:
`python tuxml_kci.py --config randconfig --kernel_version 4.13.3 --compiler gcc9 `
`python tuxml_kci.py --config myconfig.config --kernel_version 5.9 --compiler gcc6 `

in other words, we want to develop a script (let's call it tuxml_kci.py) that takes three things as parameters: 
 - (1) an existing configuration file .config or randconfig which will generate a configuration file .config; 
 - (2) a kernel version (eg 5.9); 
 - (3) a compiler and its version (eg gcc6)

- [x] write a skeleton of the script with argparse and the handling of parameters 
- [x] write the download/uncompress of a kernel archive, based on a version eg https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.13.3.tar.xz 
- [x] fabricate a randconfig (if the user does not explicitly give a .config file)
- [x] identify where/how to fed to kernelci a .config file as input
- [x] call kernelci in the right source folder and over the right .config 

At this step, the script should work locally... The issue is that we don't have control on the compiler version (we use the one of the user, locally) as well on many tools. 
So the basic principle and the big step 2 is to use Docker to host everything:
- [x] develop different Docker files that can support different gcc versions 
- [x] run a Docker container that would contain kernelci-core facilities and a script that has "everything" to execute the build (everything means source code, .config, etc.)
- [ ] in fact tuxml_kci will itself run the Docker

A cross-cutting aspect is the output/outcome we want...
Of course, we want to log everything, detect whether the build is a success or a failure, and also compute the size. 
In the middle-term, we want to use LAVA stuff and have other "tests" (and reports) over the kernel. 

Related TODO:
 - [ ] where is the adapted tutorial to "manually" realize the scenario above with kernelci?  (step-by-step)
